
name: NickName
main: NickName\NickName
version: 1.0.0
api: [1.0.0]
load: POSTWORLD
author: Martin77Epic
description: Nick your Name Easy
website: https://github.com/Martin77Epic/NickName
commands:
 nick:
  description: Nick your Name
  usage: "Usage: /nick"
  permission: nickname.nick.name
 unnick:
  description: Unnick your Name
  usage: "Usage: /unnick <Name>"
  permission: nickname.unnick.name
permissions:
 nickname.nick.name:
  default: op
 nickname.unnick.name:
  default: op
   
